### ISSUE TITLE
Bug about "k_out" parameter in "DataTrainingArguments"

### ISSUE THREAD

**Issue by benjpau** [wyu97/Easy-use-BART#1]
It seems that the "k_out" parameter is not defined in the "DataTrainingArguments".

Could you please check it, and what is the meaning of "k_out"?

Thanks!

Traceback (most recent call last):
  File "finetune.py", line 302, in <module>
    main()
  File "finetune.py", line 270, in main
    metrics.update(eval_top1_acc(out_pred_path, out_pred_ref, data_args.k_out)) ## top1_metrics
AttributeError: 'DataTrainingArguments' object has no attribute 'k_out'

**Comment by wyu97** [comment]
Hi, 

Thank you for pointing out the issue. It has been fixed now.
